DROP TABLE IF EXISTS business.CONTENTS;
CREATE TABLE business.CONTENTS(
    CONTENTS_ID char(10) NOT NULL,
    CONTENTS_VAL varchar(140) NOT NULL,
    UP_DT char(17),
    UP_NM varchar(20),
    RG_DT char(17),
    RG_NM varchar(20),
    CONSTRAINT pk_CONTENTS PRIMARY KEY (CONTENTS_ID)
);
COMMENT ON COLUMN business.CONTENTS.CONTENTS_ID IS 'コンテンツID';
COMMENT ON COLUMN business.CONTENTS.CONTENTS_VAL IS 'コンテンツ';
COMMENT ON COLUMN business.CONTENTS.UP_DT IS '更新日';
COMMENT ON COLUMN business.CONTENTS.UP_NM IS '更新者';
COMMENT ON COLUMN business.CONTENTS.RG_DT IS '登録日';
COMMENT ON COLUMN business.CONTENTS.RG_NM IS '登録者';
COMMENT ON TABLE business.CONTENTS IS 'コンテンツ';
