DROP TABLE IF EXISTS business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT;
CREATE TABLE business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT(
    FORMAT_TYPE char(1) NOT NULL,
    NODE_ID varchar(32) NOT NULL,
    VIEWABLE_FLG char(1) NOT NULL,
    SORT_ORDER smallint,
    UP_DT timestamp NOT NULL,
    UP_NM varchar(20) NOT NULL,
    RG_DT timestamp NOT NULL,
    RG_NM varchar(20) NOT NULL,
    VERSION bigint NOT NULL,
    CONSTRAINT pk_NODE_FORMAT_RELATIONSHIP_MANAGEMENT PRIMARY KEY (FORMAT_TYPE,NODE_ID)
);
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.FORMAT_TYPE IS '形式タイプ';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.NODE_ID IS 'ノードID';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.VIEWABLE_FLG IS '閲覧可能フラグ';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.SORT_ORDER IS '表示順';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.UP_DT IS '更新日';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.UP_NM IS '更新者';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.RG_DT IS '登録日';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.RG_NM IS '登録者';
COMMENT ON COLUMN business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT.VERSION IS 'バージョン';
COMMENT ON TABLE business.NODE_FORMAT_RELATIONSHIP_MANAGEMENT IS 'ノード形式関連付け管理';
