DROP TABLE IF EXISTS business.NODE_MANAGEMENT;
CREATE TABLE business.NODE_MANAGEMENT(
    NODE_ID varchar(32) NOT NULL,
    PARENT_NODE_ID varchar(32) NOT NULL DEFAULT 1,
    KEY varchar(128) NOT NULL,
    VALUE varchar(256),
    BLOB_FLG char(1) NOT NULL DEFAULT 0,
    UP_DT timestamp NOT NULL,
    UP_NM varchar(20) NOT NULL,
    RG_DT timestamp NOT NULL,
    RG_NM varchar(20) NOT NULL,
    VERSION bigint NOT NULL,
    CONSTRAINT pk_NODE_MANAGEMENT PRIMARY KEY (NODE_ID)
);
COMMENT ON COLUMN business.NODE_MANAGEMENT.NODE_ID IS 'ノードID';
COMMENT ON COLUMN business.NODE_MANAGEMENT.PARENT_NODE_ID IS '親ノードID';
COMMENT ON COLUMN business.NODE_MANAGEMENT.KEY IS 'キー';
COMMENT ON COLUMN business.NODE_MANAGEMENT.VALUE IS '値';
COMMENT ON COLUMN business.NODE_MANAGEMENT.BLOB_FLG IS 'BLOBフラグ';
COMMENT ON COLUMN business.NODE_MANAGEMENT.UP_DT IS '更新日';
COMMENT ON COLUMN business.NODE_MANAGEMENT.UP_NM IS '更新者';
COMMENT ON COLUMN business.NODE_MANAGEMENT.RG_DT IS '登録日';
COMMENT ON COLUMN business.NODE_MANAGEMENT.RG_NM IS '登録者';
COMMENT ON COLUMN business.NODE_MANAGEMENT.VERSION IS 'バージョン';
COMMENT ON TABLE business.NODE_MANAGEMENT IS 'ノード管理';
