DROP TABLE IF EXISTS business.BLOB_MANAGEMENT;
CREATE TABLE business.BLOB_MANAGEMENT(
    BLOB_ID varchar(32) NOT NULL,
    BLOB_DATA bytea NOT NULL,
    UP_DT timestamp NOT NULL,
    UP_NM varchar(20) NOT NULL,
    RG_DT timestamp NOT NULL,
    RG_NM varchar(20) NOT NULL,
    VERSION bigint NOT NULL,
    CONSTRAINT pk_BLOB_MANAGEMENT PRIMARY KEY (BLOB_ID)
);
COMMENT ON COLUMN business.BLOB_MANAGEMENT.BLOB_ID IS 'BLOBID';
COMMENT ON COLUMN business.BLOB_MANAGEMENT.BLOB_DATA IS 'BLOBデータ';
COMMENT ON COLUMN business.BLOB_MANAGEMENT.UP_DT IS '更新日';
COMMENT ON COLUMN business.BLOB_MANAGEMENT.UP_NM IS '更新者';
COMMENT ON COLUMN business.BLOB_MANAGEMENT.RG_DT IS '登録日';
COMMENT ON COLUMN business.BLOB_MANAGEMENT.RG_NM IS '登録者';
COMMENT ON COLUMN business.BLOB_MANAGEMENT.VERSION IS 'バージョン';
COMMENT ON TABLE business.BLOB_MANAGEMENT IS 'BLOB管理';
