DROP TABLE IF EXISTS business.CONTENTS_PLANE;
CREATE TABLE business.CONTENTS_PLANE(
    CONTENTS_ID integer NOT NULL,
    CONTENTS_VAL varchar(140) NOT NULL,
    UP_DT timestamp,
    UP_NM varchar(20),
    RG_DT timestamp,
    RG_NM varchar(20),
    VERSION bigint NOT NULL,
    CONSTRAINT pk_CONTENTS_PLANE PRIMARY KEY (CONTENTS_ID)
);
COMMENT ON COLUMN business.CONTENTS_PLANE.CONTENTS_ID IS 'コンテンツID';
COMMENT ON COLUMN business.CONTENTS_PLANE.CONTENTS_VAL IS 'コンテンツ';
COMMENT ON COLUMN business.CONTENTS_PLANE.UP_DT IS '更新日';
COMMENT ON COLUMN business.CONTENTS_PLANE.UP_NM IS '更新者';
COMMENT ON COLUMN business.CONTENTS_PLANE.RG_DT IS '登録日';
COMMENT ON COLUMN business.CONTENTS_PLANE.RG_NM IS '登録者';
COMMENT ON COLUMN business.CONTENTS_PLANE.VERSION IS 'バージョン';
COMMENT ON TABLE business.CONTENTS_PLANE IS 'コンテンツ_プレーン';
